// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-k05j1Q2W9L_s7KWjERrYzoSg0nPhKI',
    appId: '1:304107977443:web:04393b0d1cbe0a861363d6',
    messagingSenderId: '304107977443',
    projectId: 'acilservis-app',
    authDomain: 'acilservis-app.firebaseapp.com',
    storageBucket: 'acilservis-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNodiQws8wa5eJdeCq5KBFwjxEe1YVmp8',
    appId: '1:304107977443:android:17cf862710e539131363d6',
    messagingSenderId: '304107977443',
    projectId: 'acilservis-app',
    storageBucket: 'acilservis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvA2sQah8ZisAe_Q13577XxkwH9Xg30g',
    appId: '1:304107977443:ios:f0baad75dfef2fac1363d6',
    messagingSenderId: '304107977443',
    projectId: 'acilservis-app',
    storageBucket: 'acilservis-app.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe-k05j1Q2W9L_s7KWjERrYzoSg0nPhKI',
    appId: '1:304107977443:web:3b81702f784c62dd1363d6',
    messagingSenderId: '304107977443',
    projectId: 'acilservis-app',
    authDomain: 'acilservis-app.firebaseapp.com',
    storageBucket: 'acilservis-app.firebasestorage.app',
  );
}
